### ISSUE TITLE
Persistent Touch ID Keychain and Passcode on Uninstall

### ISSUE THREAD

**Issue by brbgyn** [D-32/DMPasscode#13]
Hi,

When i setup the Passcode/Touch ID successfully and then uninstall the app, when i do install it again the Passcode/Touch ID is already set up !

How can i remove the keychain before uninstalling the app ?

Or any other solution for this behavior.....

**Comment by brbgyn** [comment]
Thats what i was thinking.

The fact is that the TouchID has to be prompted only when the users are signed in an exclusive area of my app. Due to this, when they re-install it they are not logged, and the TouchID doesn't have to be asked.

Thank you for your reply.

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions{
.
.
.
     NSUserDefaults *ud = [NSUserDefaults standardUserDefaults];
     if (![ud boolForKey:@"turnTouchOff"]){
        [ud setBool:YES forKey:@"turnTouchOff"];
        [DMPasscode removePasscode];
     }
.
.
.
}
```

**Comment by D-32** [comment]
Thanks @dpopov.
Indeed the Keychain stays around and if desired has to be removed manually. The user defaults on the other hand will be removed (sometimes on the Simulator I've experienced them staying around though). So by having a flag inside the user defaults you can detect if it's a fresh install.
