### ISSUE TITLE
Update flow when confirming passcode

### ISSUE THREAD

**Issue by obuseme** [D-32/DMPasscode#16]
This is a great project, I love it and am working on including it with my app.

Would you be open to accepting a PR that changes the flow slightly when a user enters a mismatched passcode on the "Confirm" screen?  Rather than dismissing the passcodeViewController, I'd like it to instead prompt the user again for a new passcode, with an error message indicating that the "passcodes did not match."

**Comment by D-32** [comment]
Yeah that would be a better approach and would improve the UX.
Go ahead :)
