### ISSUE TITLE
Convert DMPasscodeInternalViewController to use Autolayout

### ISSUE THREAD

**Issue by obuseme** [D-32/DMPasscode#17]
Right now, DMPasscodeInternalViewController does not use autolayout.  As a result the UI elements are not centered on screen if you rotate the device while the passcode view controller is visible, and depending on how you modify the localized strings, if they get too big, the UILabels don't grow.

This is another one I need, and I'm working on a fix now.  If you're open to it, I can submit a PR.  Thanks again.

**Comment by D-32** [comment]
My use case was portrait only and just one localisation. I can see that people now use DMPasscode for more complex use cases than me.
I'll update the code to be more flexible. Should have some time later today.

**Comment by obuseme** [comment]
Thanks a ton for the quick help, and new release.  Literally building 1.3.0
into my project now.  Rock on.

**Comment by D-32** [comment]
Be sure to add the project here: https://www.cocoacontrols.com/controls/dmpasscode :)
