### ISSUE TITLE
Set modalPresentationStyle

### ISSUE THREAD

**Issue by obuseme** [D-32/DMPasscode#19]
Would you consider exposing the ability to set the modalPresentationStyle on the DMPasscodeInternalNavigationController somehow?  I don't really have a good idea how to do it, but I would like to set it to UIModalPresentationFormSheet

Playing around with the code, I get my desired behavior if I set the modalPresentationStyle here: https://github.com/D-32/DMPasscode/blob/master/Pod/Classes/DMPasscode.m#L137

Thoughts?

**Comment by D-32** [comment]
I guess you're using it for iPad, right? We could also just say that for iPad it's always as a form sheet. So no customisation would be needed. I don't think you would want anything else.

**Comment by obuseme** [comment]
That would work.  Rather than hard code it to iPad only, how about making it size class based because I would want this behavior as well on the iPhone 6+  in Landscape.

**Comment by D-32** [comment]
I don't think UIModalPresentationFormSheet works on the phone? I just tried it on the 6+ simulator and it didn't present it as a form sheet.

**Comment by obuseme** [comment]
Let me put together a demo tonight, and ill either post it as a sample project, or link a quicktime video to show the behavior I'm seeing - try to indicate what I'm trying to achieve.

**Comment by Nomad00** [comment]
I put together a basic sample project which forces `DMPasscodeInternalNavigationController` to have a modal presentation style of `UIModalPresentationFormSheet` all the time. https://github.com/Nomad00/ModalDMPasscode

Things of note with this:
- iPhones running iOS 7 & iOS 8, in both portrait & landscape, handle this as full screen modal.
- iPhone 6+ in landscape will present as a form sheet.
- All iPads will present as a form sheet, all the time.

**Comment by obuseme** [comment]
Nice, thanks @Nomad00   Looks good to me.

**Comment by D-32** [comment]
Awesome, thanks for your work!

**Comment by obuseme** [comment]
Just need a new release and updated podspec when you get a chance.  thx

**Comment by D-32** [comment]
Done -> 2.0.0
