### ISSUE TITLE
Differentiate "cancel" versus "failure" in completion callback

### ISSUE THREAD

**Issue by obuseme** [D-32/DMPasscode#22]
Right now, the completion block passes a binary parameter - either success or failure.  If the user "cancels" the DMPasscode screen, "NO" is returned with the completion block.  I have a use case where I need to differentiate Cancelled versus Failed, and there's no way to do that now.  I put a bunch of thought into DMPasscode and couldn't really figure out a good non-API-breaking change to do that.  I like the idea of either 1) a second parameter with the completion block of type NSError, or 2) change what the completion block returns from BOOL to a custom Enum with 3 possible values: success, fail, or cancelled (that would be the more Swifty/functional way, right :P ).  The only drawback with those is that there API breaking changes - to move away from a simple Bool returned.  Thoughts?

**Comment by D-32** [comment]
How about having BOOL:authenticated + NSError:error.


|  |authenticated  |error|
|---|---|---|
|Code ok  |YES  |nil  | 
|Code false  |NO  |NSError  | 
|Cancelled  |NO  |nil  |

So in most cases all you need to do in code is
	
	{
		if (authenticated) {
			// open hidden content
		}
	}
	
And if you're interested in if it got cancelled or not you can check if errr is nil.

**Comment by obuseme** [comment]
That would totally work!  Are you going to write it, or do you want me to
submit a PR?

**Comment by D-32** [comment]
You seem very motivated, so go ahead. I'm quite busy with other stuff...

**Comment by obuseme** [comment]
I left the BOOL named "success" because authenticated would not be a correct name in the case that the user was only setting up their passcode.
