### ISSUE TITLE
Swift?

### ISSUE THREAD

**Issue by thomascsorbamedia** [D-32/DMPasscode#31]
Hi, i have imported the pod into my swift project but i'm not familiar with objective-c.
How can i use these functions (assign setup to correct controller, change styles etc. )
Thanks in advance

**Comment by D-32** [comment]
This document should help you: https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html
Or this: http://michal.codes/integrating-cocoapods-with-a-swift-project/
You should then be able to use the methods of the library like you're used to.

**Comment by thomascsorbamedia** [comment]
Other question, is there a way to disable the fingerprint popup, i always want to show the passcode.
Thanks for your links, it works now.

**Comment by D-32** [comment]
Currently, no, that's not possible. Shouldn't be too hard though to add a new property for that.

**Comment by thomascsorbamedia** [comment]
i will look for a solution, i will send it to you if i found it if you want :)

**Comment by D-32** [comment]
cool, thx :)

**Comment by thomascsorbamedia** [comment]
Maybe you know the solution, i'm trying to rebuild the view controller in swift but my code is wrong and i can't seem to figure out how to fix it.

```
@IBAction func CheckPass(sender: UIButton) {
    DMPasscode.showPasscodeInViewController(self, completion: (succes: Bool, error: NSError?) -> ()) {
        if success != nil {
            println("passcode success")
        } else {
            if error != nil {
                println("passcode fail")
            } else {
                println("passcode cancelled")
            }
        }
    }
}
```

**Comment by D-32** [comment]
What do you mean with your code is wrong? Error messages?

**Comment by thomascsorbamedia** [comment]
it breaks on this piece of code 
    -(void)closeAndNotify:(BOOL)success withError:(NSError *)error {
        [_passcodeViewController dismissViewControllerAnimated:YES completion:^() {
            _completion(success, error);
        }];
    }

i think my completion block is wrong
there are no error messages except "(lldb)"

when i close the setup it also breaks on this code

```
- (void)close:(id)sender {
[_input resignFirstResponder];
[self dismissViewControllerAnimated:YES completion:nil];
[_delegate canceled];
}
```

**Comment by thomascsorbamedia** [comment]
Sorry, it works now, little error in completion block and i forgot to add the delegate function in my app delegate. Thanks for the help.

**Comment by D-32** [comment]
Awesome! :)
