### ISSUE TITLE
Disable fingerprint

### ISSUE THREAD

**Issue by thomascsorbamedia** [D-32/DMPasscode#32]
I'm trying to figure out how to disable fingerprint unlock.
Any idea how i could achieve this?

**Comment by D-32** [comment]
https://github.com/D-32/DMPasscode/blob/master/Pod/Classes/DMPasscode.m#L92
In this if/else we could additionally check if a property like "disableTouchId" is set to NO. If it's set to YES, we would show the passcode view controller same way as if no touch id would be available.
I would be okay with merging something like that in, as long as it doesn't add more complexity to the API.

**Comment by thomascsorbamedia** [comment]
How, for now can i just change the statement to work for me as i want?

**Comment by D-32** [comment]
Remove the whole if (line #92 to #121) and just open the view controller instead.
So replace it with: [self openPasscodeWithMode:1 viewController:viewController];

**Comment by thomascsorbamedia** [comment]
other thingy, on ipad it only shows for like half of the screen, where can i find how to change that?
sorry for al the questions, there is some pressure on the project

**Comment by D-32** [comment]
https://github.com/D-32/DMPasscode/blob/master/Pod/Classes/DMPasscode.m#L143
At some point we introduced that the VC should be presented as a form sheet. Which in my opinion makes more sense on an iPad.
Basically, if you remove this line it should also be full screen on the iPad.

**Comment by thomascsorbamedia** [comment]
You are a hero, thanks
