### ISSUE TITLE
Double init on iphone?

### ISSUE THREAD

**Issue by thomascsorbamedia** [D-32/DMPasscode#33]
Hi, 
I've setup al the functions etc. but there is a bug and i can't figure it out.
On Ipad everything works fine, i can setup and check the passcode, however on iphone i get the check screen twice which is weird because there is nothing different for iphone, nothing extra or something.
(my app is for iphone and ipad combined with auto layout)

Thanks in advance

**Comment by D-32** [comment]
Why not try debugging it your self and see where the calls are coming from when presenting the view controller?

**Comment by thomascsorbamedia** [comment]
I figured out that there is a problem when i present the passcode check view. on ipad & iphone it is the same, when it is fullscreen it appears 2 times. if i present it as UIModalPresentationFormSheet it only shows 1 time on ipad, but it still goes fullscreen on iphone and therefore shows 2 times on iphone.

**Comment by thomascsorbamedia** [comment]
I fixed it by changing the presentation style, and i added a little if statement so i can show the passcode stuff in different ways on different devices. here is my small fix

```
if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad) {
    [nc setModalPresentationStyle:UIModalPresentationFormSheet];
} else {
    [nc setModalPresentationStyle:UIModalPresentationOverCurrentContext];
}
```
