### ISSUE TITLE
Passcode remains in keychain

### ISSUE THREAD

**Issue by thomascsorbamedia** [D-32/DMPasscode#35]
Hi, i found out that when i reinstall my app (install, remove, install) that the passcode is still in keychain, this is, in my case not wanted. I know i can remove the passcode that is not the problem. but if i reinstall the app it breaks because there should be no passcode available, only the setup should be available.

Any idea how i can remove the passcode from the keychain if the app is freshly installed?

**Comment by D-32** [comment]
Seems like somebody had the same issues as you a while ago: https://github.com/D-32/DMPasscode/issues/13

**Comment by brbgyn** [comment]
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions{
.
.
.
     NSUserDefaults *ud = [NSUserDefaults standardUserDefaults];
     if (![ud boolForKey:@"turnTouchOff"]){
        [ud setBool:YES forKey:@"turnTouchOff"];
        [DMPasscode removePasscode];
     }
.
.
.
}
```
