### ISSUE TITLE
Non-empty localizedReason must be provided

### ISSUE THREAD

**Issue by ivanstojkovicapps** [D-32/DMPasscode#4]
Hi,

i am getting Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Non-empty localizedReason must be provided.'. I have the entry for "dmpasscode_touchid_reason" in my localisable strings, but i think it uses the one from the bundle.
I am not using cocoa pods, i've copied the files.

We could pass the reason to the Singleton and the problem is solved. Is this one known issue?

regards Ivan

**Comment by NehaEnstrapp** [comment]
I am also getting the same issue. Any solution for this?
